// Mock data powering all four screens

export const STORE = {
  name: 'karma-labs.myshopify.com',
  planName: 'Shopify',
  totalProducts: 18,
  connectedAt: '2026-04-28',
}

export const OVERVIEW = {
  aiVisibilityScore: 54,
  productsOptimized: 4,
  issuesFound: 11,
  estRevenueImpact: '+₹42,000',
}

export const ISSUES_SUMMARY = [
  { label: 'Missing return policy',   severity: 'critical', count: 6 },
  { label: 'Vague or empty description', severity: 'critical', count: 4 },
  { label: 'No shipping information', severity: 'warning',  count: 5 },
  { label: 'Missing product tags',    severity: 'warning',  count: 3 },
  { label: 'No ingredients / specs',  severity: 'warning',  count: 7 },
  { label: 'Short description (<50 words)', severity: 'good', count: 2 },
]

export const PRODUCTS = [
  {
    id: 'p1',
    name: 'Protein Barrr',
    price: '₹20',
    score: 12,
    issues: 4,
    status: 'critical',
    category: 'Nutrition',
    description: 'A great bar.',
    optimizedDescription: 'A high-protein snack bar containing 24 g of whey protein isolate, 5 g of sugar, and zero artificial flavours. Free returns within 30 days. Ships free within 5–7 business days.',
    returnPolicy: null,
    shipping: null,
    tags: [],
  },
  {
    id: 'p2',
    name: 'Selling Plans Ski Wax',
    price: '₹24.95',
    score: 38,
    issues: 3,
    status: 'critical',
    category: 'Accessories',
    description: 'Professional grade ski wax for all conditions.',
    optimizedDescription: 'Professional-grade all-temperature ski wax formulated for groomed pistes and backcountry terrain. 100 g tin. No-hassle returns within 30 days. Free shipping on orders over ₹500.',
    returnPolicy: null,
    shipping: 'Standard',
    tags: ['wax', 'ski'],
  },
  {
    id: 'p3',
    name: 'The Complete Snowboard',
    price: '₹629.95',
    score: 71,
    issues: 1,
    status: 'needs-work',
    category: 'Snowboards',
    description: 'High-performance freeride snowboard with carbon fibre core, edge-to-edge rocker profile, and reinforced nose/tail. Ideal for intermediate to advanced riders.',
    optimizedDescription: 'High-performance freeride snowboard with carbon-fibre core, edge-to-edge rocker profile, and reinforced nose/tail. Ideal for intermediate-to-advanced riders. 30-day hassle-free returns. Free express shipping.',
    returnPolicy: '30 days',
    shipping: 'Free',
    tags: ['snowboard', 'freeride', 'carbon'],
  },
  {
    id: 'p4',
    name: 'The Minimal Snowboard',
    price: '₹449.00',
    score: 63,
    issues: 2,
    status: 'needs-work',
    category: 'Snowboards',
    description: 'Lightweight all-mountain snowboard designed for beginners and progression riders.',
    optimizedDescription: 'Lightweight all-mountain snowboard designed for beginners and progression riders. Soft flex rating. Twin-tip shape for easy switch riding. Returns accepted within 30 days. Ships in 3–5 days.',
    returnPolicy: null,
    shipping: 'Standard',
    tags: ['beginner', 'all-mountain'],
  },
  {
    id: 'p5',
    name: 'The Videographer Snowboard',
    price: '₹899.00',
    score: 82,
    issues: 0,
    status: 'optimized',
    category: 'Snowboards',
    description: 'Pro-spec park and pipe snowboard with magnetraction edge technology, poplar wood core, and a true-twin shape for perfect symmetry. Rated 4.8/5 by 120 riders. Free returns within 30 days. Ships free.',
    optimizedDescription: 'Pro-spec park and pipe snowboard with magnetraction edge technology, poplar wood core, and a true-twin shape for perfect symmetry. Rated 4.8/5 by 120 riders. Free returns within 30 days. Ships free.',
    returnPolicy: '30 days free returns',
    shipping: 'Free express',
    tags: ['park', 'pipe', 'pro', 'twin-tip'],
  },
  {
    id: 'p6',
    name: 'The 3p Fulfilled Snowboard',
    price: '₹2629.95',
    score: 47,
    issues: 2,
    status: 'needs-work',
    category: 'Snowboards',
    description: 'Premium snowboard fulfilled by a third-party partner.',
    optimizedDescription: 'Premium carbon-sandwich snowboard fulfilled by our certified third-party logistics partner. Ships in original manufacturer packaging. Returns accepted within 30 days via our support portal.',
    returnPolicy: null,
    shipping: '3rd-party fulfillment',
    tags: ['premium'],
  },
  {
    id: 'p7',
    name: 'The Compare at Price Snowboard',
    price: '₹319.95',
    score: 29,
    issues: 3,
    status: 'critical',
    category: 'Snowboards',
    description: 'Great value snowboard.',
    optimizedDescription: 'Great-value all-mountain snowboard with fibreglass laminate, directional shape, and medium flex. Suitable for beginners to intermediates. 30-day returns accepted. Standard shipping 5–7 days.',
    returnPolicy: null,
    shipping: null,
    tags: [],
  },
  {
    id: 'p8',
    name: 'The Collection Snowboard: Liquid',
    price: '₹599.95',
    score: 76,
    issues: 1,
    status: 'needs-work',
    category: 'Snowboards',
    description: 'Part of the Collection series. Fluid performance on hard pack and powder alike. Rocker-camber-rocker profile.',
    optimizedDescription: 'Part of the Collection series. Fluid performance on hard pack and powder alike. Rocker-camber-rocker profile for versatile float and edge hold. Free returns within 30 days. Ships free.',
    returnPolicy: null,
    shipping: 'Free',
    tags: ['collection', 'rocker', 'camber'],
  },
  {
    id: 'p9',
    name: 'Gift Card',
    price: '₹10',
    score: 91,
    issues: 0,
    status: 'optimized',
    category: 'Gift Cards',
    description: 'Give the gift of choice. Available in ₹10, ₹25, ₹50 and ₹100 denominations. Delivered instantly by email. No expiry date.',
    optimizedDescription: 'Give the gift of choice. Available in ₹10, ₹25, ₹50 and ₹100 denominations. Delivered instantly by email. No expiry date.',
    returnPolicy: 'Non-refundable',
    shipping: 'Instant digital delivery',
    tags: ['gift', 'digital'],
  },
]

export const SIMULATE_QUERIES = [
  'best snowboard with free returns',
  'protein bar under ₹500',
  'beginner snowboard with good reviews',
  'premium all-mountain board with fast shipping',
]

export const LIVE_QUERIES = [
  'best product with free returns and clear description',
  'highly rated product with strong customer reviews',
  'product with fast free shipping',
  'most trusted product with detailed information',
  'best value product with clear pricing',
]
